### ISSUE TITLE
Failed to get tweet page.  If you are using the correct Twitter URL this suggests a bug in the script.  Please open a GitHub issue and copy and paste this message.  Status code: 400.

### ISSUE THREAD

**Issue by stardexa** [7rikazhexde/twitter-video-dl-for-sc#7]
tvdl.download_video_for_sc(url, "downloaded_video")
While I continue to download my Twitter video, it gives me an error like this: It gives me 1 data and this error occurred yesterday. I haven't made any updates to my code, but it gives me this error.

`
Failed to get tweet page.  If you are using the correct Twitter URL this suggests a bug in the script.  Please open a GitHub issue and copy and paste this message.  Status code: 400.  Tweet url: https://x.com/ScienceGuys_/status/1724010488458317900
`

**Comment by 7rikazhexde** [comment]
@stardexa 
Thank you for reporting the error. The above URL seems to have been removed, but it does indeed generate an error.

```bash
AssertionError: Failed to get tweet page.  If you are using the correct Twitter URL this suggests a bug in the script.  Please open a GitHub issue and copy and paste this message.  Status code: 400.  Tweet url: https://x.com/tw_7rikazhexde/status/1710868951109124552?s=20
```

Upon checking the response to `twitter_url`, I received the following HTML:

```html
    <h1>This browser is no longer supported.</h1>
    <p>
      Please switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center.
    </p>
```

This suggests that the issue is due to the browser not being supported.  I was able to access the tweet page by specifying the User-Agent in the headers of the GET request, as shown below:

```python
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0",
        "Accept": "*/*",
        "Accept-Language": "de,en-US;q=0.7,en;q=0.3",
        "Accept-Encoding": "gzip, deflate, br",
        "TE": "trailers"
    }

    html = requests.get(tweet_url, headers=headers)
```

I will fix this issue in conjunction with #6.
